interface ProductInput {
  name: string;
  price: number;
  oldPrice?: number;
  image: string;
  category: string;
  rating: number;
  reviews?: number;
  badge?: string;
  badgeClass?: string;
  description?: string;
}

export const PRODUCTS: ProductInput[] = [
  // ===== BATS =====
  { name: "MRF CHASE MASTER", price: 100, oldPrice: 149, image: "/images/products/bat-english-willow-mrf-chase-master.webp", category: "bats", rating: 4.5, reviews: 120, badge: "Value", description: "Entry-level English willow bat for aspiring players." },
  { name: "MRF GOLD", price: 0, image: "/images/products/bat-english-willow-mrf-gold.webp", category: "bats", rating: 4.3, reviews: 45, description: "Premium MRF bat with balanced pickup." },
  { name: "MRF GRAND EDITION", price: 580.99, image: "/images/products/bat-english-willow-mrf-grand-edition.webp", category: "bats", rating: 4.9, reviews: 210, badge: "Premium", description: "Top-grade English willow. Used by professionals worldwide." },
  { name: "MRF GRAND 2", price: 0, image: "/images/products/bat-english-willow-mrf-grand-2.webp", category: "bats", rating: 4.6, reviews: 78, description: "Professional grade bat with large sweet spot." },
  { name: "MASTER 9000 (SS)", price: 139.99, image: "/images/products/bat-english-willow-master-9000.webp", category: "bats", rating: 4.4, reviews: 95, description: "Lightweight bat with excellent pick-up and balance." },
  { name: "MASTER 2000 (SS)", price: 490, image: "/images/products/bat-english-willow-master-2000.webp", category: "bats", rating: 4.7, reviews: 156, description: "Premium SS bat crafted for power hitters." },
  { name: "THALA 20 (SS)", price: 599.99, image: "/images/products/bat-english-willow-thala-20.webp", category: "bats", rating: 4.8, reviews: 189, badge: "Premium", description: "Limited edition bat with superior willow grade." },
  { name: "ORANGE (SS)", price: 329.99, image: "/images/products/bat-english-willow-orange.webp", category: "bats", rating: 4.6, reviews: 134, description: "Striking design with exceptional performance." },
  { name: "POWERPLUS (SS)", price: 2959, image: "/images/products/bat-english-willow-powerplus.webp", category: "bats", rating: 4.9, reviews: 87, badge: "Premium", description: "Elite-grade bat crafted for professional cricketers." },
  { name: "DEVIL RED (SS)", price: 499.99, image: "/images/products/bat-english-willow-devil-red.webp", category: "bats", rating: 4.7, reviews: 203, description: "Power-packed bat with aggressive profile." },
  { name: "RICHARD (SS)", price: 3499, image: "/images/products/bat-english-willow-richard.webp", category: "bats", rating: 5.0, reviews: 56, badge: "Premium", description: "Ultra-premium bat handcrafted from finest English willow." },
  { name: "WORLD CUP EDITION (SS)", price: 360.99, image: "/images/products/bat-english-willow-world-cup-edition.webp", category: "bats", rating: 4.7, reviews: 167, description: "Special edition bat commemorating cricket's biggest tournament." },
  { name: "FIRE (SS)", price: 225.9, image: "/images/products/bat-english-willow-fire.webp", category: "bats", rating: 4.5, reviews: 112, description: "Mid-range bat with excellent driving capabilities." },
  { name: "VERTU 15 (SS)", price: 449.99, image: "/images/products/bat-english-willow-vertu-15.webp", category: "bats", rating: 4.7, reviews: 98, description: "Premium bat with thick edges and balanced pick-up." },
  { name: "TON LEGEND 20 (SS)", price: 10, image: "/images/products/bat-english-willow-ton-legend-20.webp", category: "bats", rating: 4.2, reviews: 34, description: "Budget-friendly bat for casual and practice use." },
  { name: "PRESALM (SS)", price: 319.99, image: "/images/products/bat-english-willow-presalm.webp", category: "bats", rating: 4.5, reviews: 88, description: "Well-balanced bat suitable for all formats." },
  { name: "THUNDER (SS)", price: 314, image: "/images/products/bat-english-willow-thunder.webp", category: "bats", rating: 4.5, reviews: 123, description: "Powerful bat with responsive middle and pickup." },
  { name: "SKY 30 21 (SS)", price: 499.99, image: "/images/products/bat-english-willow-sky-30-21.webp", category: "bats", rating: 4.7, reviews: 145, description: "High-performance bat with superior stroke play." },
  { name: "SG SUNNY TONNY ARC 4G", price: 499.99, image: "/images/products/bat-english-willow-sg-sunny-tonny-arc-4g.webp", category: "bats", rating: 4.8, reviews: 178, badge: "Bestseller", description: "SG's flagship bat with advanced profile for aggressive batting." },
  { name: "SG TRIPLE CROWN EXTREME", price: 449.99, image: "/images/products/bat-english-willow-sg-triple-crown-extreme.webp", category: "bats", rating: 4.7, reviews: 134, description: "Premium SG bat with triple reinforcement for durability." },
  { name: "SG SAVAGE EXTREME", price: 430.99, image: "/images/products/bat-english-willow-sg-savage-extreme.webp", category: "bats", rating: 4.6, reviews: 112, description: "Aggressive bat designed for power hitting." },
  { name: "KOOKABURRA GHOST PRO 1.1", price: 274.9, image: "/images/products/bat-english-willow-kookaburra-ghost-pro-11.webp", category: "bats", rating: 4.6, reviews: 156, description: "Kookaburra's iconic bat with pro-level performance." },
  { name: "REEBOK SUPER DRIVE PRO", price: 294.99, image: "/images/products/bat-english-willow-reebok-super-drive-pro.webp", category: "bats", rating: 4.5, reviews: 89, description: "Reebok bat engineered for powerful drives." },
  { name: "SS-GT10", price: 410.9, image: "/images/products/bat-english-willow-ss-gt10.webp", category: "bats", rating: 4.6, reviews: 67, description: "Premium GT series bat with excellent balance." },
  { name: "BAS CLUB", price: 119.99, image: "/images/products/bat-english-willow-bas-club.webp", category: "bats", rating: 4.3, reviews: 56, description: "Club-level bat ideal for amateur cricketers." },
  { name: "DSC SPLIT 222", price: 248, image: "/images/products/bat-english-willow-dsc-split-222.webp", category: "bats", rating: 4.5, reviews: 78, description: "DSC bat with split profile for enhanced performance." },
  { name: "DSC-BL 200", price: 129.99, image: "/images/products/bat-english-willow-dsc-bl-200.webp", category: "bats", rating: 4.3, reviews: 45, description: "Entry-level bat from DSC for developing players." },
  { name: "DSC-XLITE 5.0", price: 19.99, image: "/images/products/bat-english-willow-dsc-xlite-50.webp", category: "bats", rating: 4.0, reviews: 23, description: "Budget-friendly bat for young beginners." },
  { name: "BDM JAI HO", price: 24.99, image: "/images/products/bat-english-willow-bdm-jai-ho.webp", category: "bats", rating: 4.1, reviews: 67, description: "Affordable bat for school and casual cricket." },
  { name: "GM HYPR 444", price: 300, image: "/images/products/bat-english-willow-gm-hypr-444.webp", category: "bats", rating: 4.6, reviews: 92, description: "GM Hypra series with advanced sweet spot technology." },
  { name: "GM DIAMOND 444", price: 0, image: "/images/products/bat-english-willow-gm-diamond-444.webp", category: "bats", rating: 4.4, reviews: 34, description: "GM Diamond series with premium willow grade." },
  { name: "GM BRAVA 444", price: 309.99, image: "/images/products/bat-english-willow-gm-brava-444.webp", category: "bats", rating: 4.5, reviews: 78, description: "GM bat with bold design and powerful performance." },
  { name: "GRAY NICHOLLS COBRA EDITION 5", price: 414, image: "/images/products/bat-english-willow-gray-nicholls-cobra-edition-5.webp", category: "bats", rating: 4.7, reviews: 145, badge: "Bestseller", description: "Limited edition Cobra bat with superior balance and power." },
  { name: "NEW BALANCE TC PRO", price: 430.99, image: "/images/products/bat-english-willow-new-balance-tc-pro.webp", category: "bats", rating: 4.6, reviews: 89, description: "New Balance pro bat with advanced carbon handle." },
  { name: "AZTRAL HARROW", price: 149.9, image: "/images/products/bat-english-willow-aztral-harrow.webp", category: "bats", rating: 4.3, reviews: 56, description: "Harwood bat ideal for practice and club cricket." },
  { name: "AZTRAL SIZE 6", price: 134.99, image: "/images/products/bat-english-willow-aztral-size-6.webp", category: "bats", rating: 4.2, reviews: 34, description: "Youth size 6 bat for junior cricketers." },
  { name: "AZTRAL SIZE 5", price: 124.9, image: "/images/products/bat-english-willow-aztral-size-5.webp", category: "bats", rating: 4.2, reviews: 28, description: "Youth size 5 bat for growing players." },
  { name: "AZTRAL SIZE 4", price: 119.99, image: "/images/products/bat-english-willow-aztral-size-4.webp", category: "bats", rating: 4.1, reviews: 22, description: "Youth size 4 bat for junior development." },
  { name: "AZTRAL SIZE 3", price: 114, image: "/images/products/bat-english-willow-aztral-size-3.webp", category: "bats", rating: 4.1, reviews: 18, description: "Youth size 3 bat for beginner cricketers." },
  { name: "MRF MASTER", price: 99.95, image: "/images/products/bat-kashmir-willow-mrf-master.webp", category: "bats", rating: 4.3, reviews: 67, description: "Kashmir willow bat with excellent durability." },
  { name: "RNS KIDS BAT KASHMIR WILLOW", price: 74.99, image: "/images/products/bat-kashmir-willow-rns-kids-bat-kashmir-willow.webp", category: "bats", rating: 4.2, reviews: 45, description: "Kids bat made from Kashmir willow for young players." },
  { name: "CA COCONUT BAT", price: 164.99, image: "/images/products/bat-tapeball-tennis-ca-coconut-bat.webp", category: "bats", rating: 4.4, reviews: 56, badge: "Value", description: "Tapeball bat with robust construction for street cricket." },
  { name: "CA TAPE BAT", price: 9.99, image: "/images/products/bat-tapeball-tennis-ca-tape-bat.webp", category: "bats", rating: 4.0, reviews: 34, description: "Budget tapeball bat for casual street cricket." },
  { name: "AS KERALA SCOOP BATS", price: 134.99, image: "/images/products/bat-tapeball-tennis-as-kerala-scoop-bats.webp", category: "bats", rating: 4.3, reviews: 78, description: "Hard tennis ball scoop bat for tennis ball cricket." },
  { name: "MIDWICKET GALAXIAN SCOOP BATS", price: 124.99, image: "/images/products/bat-tapeball-tennis-midwicket-galaxian-scoop-bats.webp", category: "bats", rating: 4.3, reviews: 45, description: "Scoop bat designed for hard tennis ball play." },
  { name: "7F SCOOP BATS", price: 124.99, image: "/images/products/bat-tapeball-tennis-7f-scoop-bats.webp", category: "bats", rating: 4.2, reviews: 34, description: "Specialized scoop bat for tennis ball cricket." },
  { name: "FIPCO PLASTIC BAT", price: 0, image: "/images/products/bat-tapeball-tennis-fipco-plastic-bat.webp", category: "bats", rating: 3.8, reviews: 12, description: "Plastic bat for indoor practice and beginners." },

  // ===== PROTECTIVE GEAR =====
  { name: "ELBOW GUARD MATCH", price: 17.99, image: "/images/products/protective-upper-body-elbow-guard-match.webp", category: "protection", rating: 4.3, reviews: 56, description: "Match-quality elbow guard with comfortable fit." },
  { name: "ELBOW GUARD TON 1.0 31", price: 24.9, image: "/images/products/protective-upper-body-elbow-guard-ton-10-31.webp", category: "protection", rating: 4.4, reviews: 34, description: "Premium elbow guard with extended coverage." },
  { name: "ELBOW GUARD MILLENIUM", price: 17.09, image: "/images/products/protective-upper-body-elbow-guard-millenium.webp", category: "protection", rating: 4.2, reviews: 28, description: "Youth elbow guard for growing cricketers." },
  { name: "MOONWALKR CHEST GUARD", price: 34.99, image: "/images/products/protective-upper-body-moonwalkr-chest-guard.webp", category: "protection", rating: 4.3, reviews: 45, description: "Youth chest guard offering reliable upper body protection." },
  { name: "CHEST GUARD", price: 29.99, image: "/images/products/protective-upper-body-chest-guard.webp", category: "protection", rating: 4.2, reviews: 34, description: "Essential chest protection for young players." },
  { name: "TRUNK SUPPORTER", price: 17.99, image: "/images/products/protective-lower-body-trunk-supporter.webp", category: "protection", rating: 4.1, reviews: 67, description: "Comfortable trunk supporter for cricket." },
  { name: "ABDO GUARD FEMALE", price: 14.99, image: "/images/products/protective-lower-body-abdo-guard-female.webp", category: "protection", rating: 4.3, reviews: 23, description: "Abdominal guard designed for female cricketers." },
  { name: "ABDO GUARD MALE", price: 14.09, image: "/images/products/protective-lower-body-abdo-guard-male.webp", category: "protection", rating: 4.2, reviews: 89, description: "Standard abdominal guard for male cricketers." },
  { name: "ABDO GUARD", price: 14.99, image: "/images/products/protective-lower-body-abdo-guard.webp", category: "protection", rating: 4.2, reviews: 56, description: "Youth abdominal guard with ergonomic design." },
  { name: "SPORTSFOLIO-ABDO GUARD", price: 11.9, image: "/images/products/protective-lower-body-sportsfolio-abdo-guard.webp", category: "protection", rating: 4.1, reviews: 34, description: "Value abdominal guard from Sportsfolio." },
  { name: "YONKER ABDO GUARD", price: 14.99, image: "/images/products/protective-lower-body-yonker-abdo-guard.webp", category: "protection", rating: 4.2, reviews: 28, description: "Yonker abdominal guard with comfortable padding." },
  { name: "THIGH GUARD COMBO", price: 54, image: "/images/products/protective-lower-body-thigh-guard-combo.webp", category: "protection", rating: 4.4, reviews: 34, description: "Youth thigh guard combo for complete leg protection." },
  { name: "MOONWALKR THIGH GUARD COMBO", price: 49.99, image: "/images/products/protective-lower-body-moonwalkr-thigh-guard-combo.webp", category: "protection", rating: 4.4, reviews: 45, description: "Premium thigh guard combo with maximum protection." },
  { name: "SG-BL COLORED PADS", price: 990, image: "/images/products/protective-lower-body-sg-bl-colored-pads.webp", category: "protection", rating: 4.8, reviews: 56, badge: "Premium", description: "Professional colored batting pads with top-grade protection." },
  { name: "SG-BL XTREME", price: 94.99, image: "/images/products/protective-lower-body-sg-bl-xtreme.webp", category: "protection", rating: 4.5, reviews: 78, description: "Extreme protection pads with advanced padding technology." },
  { name: "CEIL COLORED", price: 100, image: "/images/products/protective-lower-body-ceil-colored.webp", category: "protection", rating: 4.4, reviews: 34, description: "Colored leg guards with robust protection." },
  { name: "YONKER-COLORED HELMETS", price: 99.99, image: "/images/products/protective-helmets-yonker-colored-helmets.webp", category: "protection", rating: 4.5, reviews: 67, description: "Yonker helmet with colored finish and titanium grill." },
  { name: "MOONWALKR HELMET", price: 106, image: "/images/products/protective-helmets-moonwalkr-helmet.webp", category: "protection", rating: 4.6, reviews: 89, description: "Premium helmet with superior impact protection." },
  { name: "FORMA HELMET", price: 99, image: "/images/products/protective-helmets-forma-helmet.webp", category: "protection", rating: 4.4, reviews: 56, description: "Forma helmet with lightweight design and secure fit." },
  { name: "SHREY HELMET", price: 74.99, image: "/images/products/protective-helmets-shrey-helmet.webp", category: "protection", rating: 4.5, reviews: 134, badge: "Bestseller", description: "Popular Shrey helmet with excellent visibility and protection." },
  { name: "SHREY NECK GUARD", price: 19.09, image: "/images/products/protective-helmets-shrey-neck-guard.webp", category: "protection", rating: 4.3, reviews: 45, description: "Neck guard attachment compatible with Shrey helmets." },

  // ===== GLOVES & WICKET KEEPING =====
  { name: "MRF BIG CHASE MASTER", price: 130.99, image: "/images/products/gloves-batting-mrf-big-chase-master.webp", category: "gloves", rating: 4.6, reviews: 89, description: "Premium MRF batting gloves with superior padding." },
  { name: "MRF LEGEND VK", price: 100, image: "/images/products/gloves-batting-mrf-legend-vk.webp", category: "gloves", rating: 4.5, reviews: 67, description: "Signature VK edition batting gloves for elite performance." },
  { name: "MRF GRAND 20", price: 14.99, image: "/images/products/gloves-batting-mrf-grand-20.webp", category: "gloves", rating: 4.0, reviews: 23, description: "Entry-level MRF gloves for practice sessions." },
  { name: "BIG POWERPLUS (SS)", price: 64.99, image: "/images/products/gloves-batting-big-powerplus.webp", category: "gloves", rating: 4.4, reviews: 56, description: "SS batting gloves with reinforced finger protection." },
  { name: "6/6 GOLDEN GUTSY (SS)", price: 41.99, image: "/images/products/gloves-batting-6-6-golden-gutsy.webp", category: "gloves", rating: 4.3, reviews: 34, description: "Durable batting gloves with excellent grip and comfort." },
  { name: "BIG TON SUPREME (SS)", price: 0, image: "/images/products/gloves-batting-big-ton-supreme.webp", category: "gloves", rating: 4.4, reviews: 28, description: "Premium SS gloves with extended padding coverage." },
  { name: "6/6 CLUBLITE (SS)", price: 74.99, image: "/images/products/gloves-batting-6-6-clublite.webp", category: "gloves", rating: 4.4, reviews: 45, description: "Lightweight SS gloves for club cricketers." },
  { name: "RNS BIG SPORTSFOLIO", price: 99.99, image: "/images/products/gloves-batting-rns-big-sportsfolio.webp", category: "gloves", rating: 4.5, reviews: 78, badge: "Bestseller", description: "Sportsfolio branded batting gloves with pro-level protection." },
  { name: "BG PLATINO", price: 0, image: "/images/products/gloves-batting-bg-platino.webp", category: "gloves", rating: 4.3, reviews: 15, description: "Youth batting gloves for junior cricketers." },
  { name: "WK GLOVES DRAGON (SS)", price: 79.9, image: "/images/products/gloves-wicketkeeping-wk-gloves-dragon.webp", category: "gloves", rating: 4.5, reviews: 56, description: "SS wicket keeping gloves with dragon-scale grip pattern." },
  { name: "WK GLOVES TON 10 41 (SS)", price: 99.99, image: "/images/products/gloves-wicketkeeping-wk-gloves-ton-10-41.webp", category: "gloves", rating: 4.6, reviews: 45, description: "Premium SS wicket keeping gloves for match play." },
  { name: "WK PAD (SS)", price: 0, image: "/images/products/gloves-wicketkeeping-wk-pad.webp", category: "gloves", rating: 4.3, reviews: 23, description: "SS wicket keeping pads with lightweight construction." },
  { name: "RNS-WK GLOVES", price: 0, image: "/images/products/gloves-wicketkeeping-rns-wk-gloves.webp", category: "gloves", rating: 4.2, reviews: 18, description: "RNS wicket keeping gloves for recreational cricket." },
  { name: "RNS-WK COLORED PADS", price: 0, image: "/images/products/gloves-wicketkeeping-rns-wk-colored-pads.webp", category: "gloves", rating: 4.1, reviews: 12, description: "Colored wicket keeping pads from RNS." },
  { name: "Z HORSES-WK GLOVES", price: 64.99, image: "/images/products/gloves-wicketkeeping-z-horses-wk-gloves.webp", category: "gloves", rating: 4.3, reviews: 34, description: "Z Horses wicket keeping gloves with excellent dexterity." },

  // ===== CRICKET BALLS =====
  { name: "SPORTSFOLIO LEATHER PRACTICE BALLS", price: 0, image: "/images/products/balls-sportsfolio-leather-practice-balls.webp", category: "balls", rating: 4.2, reviews: 23, description: "Sportsfolio leather practice balls for net sessions." },
  { name: "SG-CLUB LEATHER", price: 25.49, image: "/images/products/balls-sg-club-leather.webp", category: "balls", rating: 4.5, reviews: 178, badge: "Bestseller", description: "SG club leather cricket ball with durable stitching." },
  { name: "SG-SHIELD 20", price: 19.99, image: "/images/products/balls-sg-shield-20.webp", category: "balls", rating: 4.4, reviews: 156, description: "SG Shield ball for practice and club cricket." },
  { name: "NIVIA BALL DOZEN", price: 54.99, image: "/images/products/balls-nivia-ball-dozen.webp", category: "balls", rating: 4.5, reviews: 89, description: "Nivia tennis ball dozen for training and recreational play." },
  { name: "CENTRE COURT-PK SIXER BALL DOZEN", price: 28.99, image: "/images/products/balls-centre-court-pk-sixer-ball-dozen.webp", category: "balls", rating: 4.3, reviews: 67, description: "Centre Court sixer ball dozen for street cricket." },
  { name: "CA SPEED TENNIS BALL", price: 13.99, image: "/images/products/balls-ca-speed-tennis-ball.webp", category: "balls", rating: 4.2, reviews: 45, description: "CA speed tennis ball for fast bowling practice." },
  { name: "AFO-YELLOW BALLS", price: 14.99, image: "/images/products/balls-afo-yellow-balls.webp", category: "balls", rating: 4.1, reviews: 34, description: "Yellow practice balls for visibility training." },
  { name: "WILSON SOFT TENNIS BALLS", price: 12.99, image: "/images/products/balls-wilson-soft-tennis-balls.webp", category: "balls", rating: 4.3, reviews: 56, description: "Wilson soft tennis balls for indoor and junior cricket." },

  // ===== APPAREL, BAGS & KITS =====
  { name: "MRF KITBAG & TROLLEYS", price: 144.99, image: "/images/products/bags-kits-mrf-kitbag-and-trolleys.webp", category: "apparel", rating: 4.6, reviews: 78, badge: "Bestseller", description: "MRF trolley kitbag with multiple compartments." },
  { name: "PROFESSIONAL WHEELIE 24 (SS)", price: 144.99, image: "/images/products/bags-kits-professional-wheelie-24.webp", category: "apparel", rating: 4.5, reviews: 56, description: "SS professional wheelie bag for all your gear." },
  { name: "MATRIX WHEELIE (SS)", price: 154.99, image: "/images/products/bags-kits-matrix-wheelie.webp", category: "apparel", rating: 4.6, reviews: 45, description: "SS Matrix wheelie bag with premium build quality." },
  { name: "BLASTER WHEELIE (SS)", price: 0, image: "/images/products/bags-kits-blaster-wheelie.webp", category: "apparel", rating: 4.4, reviews: 23, description: "SS blaster wheelie bag for travel convenience." },
  { name: "MASTER KITBAG (SS)", price: 0, image: "/images/products/bags-kits-master-kitbag.webp", category: "apparel", rating: 4.3, reviews: 18, description: "SS master kitbag for complete cricket gear storage." },
  { name: "RANGER KITBAG (SS)", price: 50.99, image: "/images/products/bags-kits-ranger-kitbag.webp", category: "apparel", rating: 4.2, reviews: 34, description: "SS ranger kitbag — compact and affordable." },
  { name: "FIRST KIT BAG (SS)", price: 60.9, image: "/images/products/bags-kits-first-kit-bag.webp", category: "apparel", rating: 4.3, reviews: 28, description: "SS first kit bag for beginner cricketers." },
  { name: "KIDS PLASTIC KIT (SS)", price: 29.99, image: "/images/products/youth-kits-kids-plastic-kit.webp", category: "apparel", rating: 4.1, reviews: 45, description: "Complete plastic kit for junior cricketers." },
  { name: "FIRST KIT (SS)", price: 190, image: "/images/products/youth-kits-first-kit.webp", category: "apparel", rating: 4.4, reviews: 34, description: "SS complete starter kit with essential equipment." },
  { name: "BIG CAMPUS", price: 0, image: "/images/products/youth-kits-big-campus.webp", category: "apparel", rating: 4.2, reviews: 15, description: "Youth campus kit for school cricketers." },
  { name: "17 BIL CLUBBLITE", price: 79.99, image: "/images/products/youth-kits-17-bil-clubblite.webp", category: "apparel", rating: 4.3, reviews: 22, description: "Youth club kit with lightweight gear." },
  { name: "FIPCO KIDS KIT", price: 29, image: "/images/products/youth-kits-fipco-kids-kit.webp", category: "apparel", rating: 4.0, reviews: 56, description: "Fipco junior kit — perfect for young beginners." },
  { name: "ADIDAS INDIAN JERSEY", price: 34.99, image: "/images/products/team-sportswear-adidas-indian-jersey.webp", category: "jerseys", rating: 4.6, reviews: 234, badge: "Bestseller", description: "Official style Indian cricket jersey by Adidas." },
  { name: "CSK JERSEY", price: 29.99, image: "/images/products/team-sportswear-csk-jersey.webp", category: "jerseys", rating: 4.5, reviews: 189, description: "CSK fan jersey for the Yellow Army." },
  { name: "MI JERSEY", price: 10, image: "/images/products/team-sportswear-mi-jersey.webp", category: "jerseys", rating: 4.4, reviews: 156, description: "Mumbai Indians fan jersey for MI supporters." },

  // ===== ACCESSORIES & TRAINING TOOLS =====
  { name: "WAX DOGM", price: 100, image: "/images/products/accessories-bat-care-wax-dogm.webp", category: "accessories", rating: 4.4, reviews: 34, description: "Premium bat wax for maintaining your bat's finish." },
  { name: "WAX 25GM / STUMP", price: 20, image: "/images/products/accessories-bat-care-wax-25gm-stump.webp", category: "accessories", rating: 4.3, reviews: 28, description: "Bat wax and stump maintenance kit." },
  { name: "TOE GUARD KIT", price: 0, image: "/images/products/accessories-bat-care-toe-guard-kit.webp", category: "accessories", rating: 4.2, reviews: 15, description: "Toe guard application kit for bat protection." },
  { name: "BAT MALLET", price: 14.99, image: "/images/products/accessories-bat-care-bat-mallet.webp", category: "accessories", rating: 4.5, reviews: 78, description: "Bat mallet for knocking-in your new cricket bat." },
  { name: "BALL MALLET", price: 14.99, image: "/images/products/accessories-bat-care-ball-mallet.webp", category: "accessories", rating: 4.4, reviews: 56, description: "Ball mallet for preparing cricket balls." },
  { name: "SIDE TAPE ROLL", price: 1.99, image: "/images/products/accessories-bat-care-side-tape-roll.webp", category: "accessories", rating: 4.1, reviews: 89, description: "Side tape for bat edge protection during play." },
  { name: "SIDE TAPE ROLL 1.75", price: 7, image: "/images/products/accessories-bat-care-side-tape-roll-175.webp", category: "accessories", rating: 4.2, reviews: 34, description: "Wider side tape roll for enhanced edge protection." },
  { name: "SCUFF SHEET", price: 7.99, image: "/images/products/accessories-bat-care-scuff-sheet.webp", category: "accessories", rating: 4.3, reviews: 23, description: "Scuff sheet for bat face protection." },
  { name: "GRIP CONE", price: 0, image: "/images/products/accessories-grips-grip-cone.webp", category: "accessories", rating: 4.1, reviews: 12, description: "Grip cone tool for easy grip installation." },
  { name: "SINGLE PREMIUM GRIP", price: 8.99, image: "/images/products/accessories-grips-single-premium-grip.webp", category: "accessories", rating: 4.3, reviews: 156, description: "Premium bat grip with superior feel and comfort." },
  { name: "GRIPS HACK", price: 17, image: "/images/products/accessories-grips-grips-hack.webp", category: "accessories", rating: 4.2, reviews: 23, description: "Multi-grip pack for customized bat handle feel." },
  { name: "MATTING GRIPS", price: 4, image: "/images/products/accessories-grips-matting-grips.webp", category: "accessories", rating: 4.1, reviews: 45, description: "Economy matting grips for basic bat handling." },
  { name: "ROBOARM SHORT", price: 40, image: "/images/products/accessories-training-roboarm-short.webp", category: "accessories", rating: 4.4, reviews: 34, description: "Short ball feeder for batting practice sessions." },
  { name: "ROBOARM LONG", price: 84.99, image: "/images/products/accessories-training-roboarm-long.webp", category: "accessories", rating: 4.5, reviews: 28, description: "Long ball feeder for varied bowling practice." },
  { name: "BATTING TEES", price: 4.99, image: "/images/products/accessories-training-batting-tees.webp", category: "accessories", rating: 4.0, reviews: 67, description: "Batting tees for stationary shot practice." },
  { name: "SPORTSFOLIO PLASTIC CONE", price: 0, image: "/images/products/accessories-training-sportsfolio-plastic-cone.webp", category: "accessories", rating: 3.8, reviews: 12, description: "Plastic cone for fielding drills." },
  { name: "STRINGING BALL", price: 19.99, image: "/images/products/accessories-training-stringing-ball.webp", category: "accessories", rating: 4.2, reviews: 34, description: "Stringing ball for hand-eye coordination training." },
  { name: "STR8BAT BATTING SENSOR", price: 199.99, image: "/images/products/accessories-training-str8bat-batting-sensor.webp", category: "accessories", rating: 4.6, reviews: 23, badge: "Premium", description: "Smart batting sensor for performance tracking and analysis." },
  { name: "TARGET STUMPS", price: 34.99, image: "/images/products/accessories-stumps-target-stumps.webp", category: "accessories", rating: 4.4, reviews: 56, description: "Target stumps for precision bowling practice." },
  { name: "GRAVITY STUMP", price: 0, image: "/images/products/accessories-stumps-gravity-stump.webp", category: "accessories", rating: 4.3, reviews: 18, description: "Self-righting gravity stumps for practice." },
  { name: "PROTOS-LIGHTING STUMP", price: 156.9, image: "/images/products/accessories-stumps-protos-lighting-stump.webp", category: "accessories", rating: 4.5, reviews: 34, description: "LED-lit stumps for night practice and matches." },
  { name: "SPORTSFOLIO PLASTIC STUMP", price: 34.99, image: "/images/products/accessories-stumps-sportsfolio-plastic-stump.webp", category: "accessories", rating: 4.0, reviews: 56, description: "Plastic stumps for safe junior cricket." },
  { name: "SPORTSFOLIO-RUBBER BASE STUMP", price: 44.99, image: "/images/products/accessories-stumps-sportsfolio-rubber-base-stump.webp", category: "accessories", rating: 4.2, reviews: 34, description: "Stumps with rubber base for stable setup." },
  { name: "SPORTSFOLIO SPRING STUMP", price: 79.99, image: "/images/products/accessories-stumps-sportsfolio-spring-stump.webp", category: "accessories", rating: 4.3, reviews: 23, description: "Spring-loaded stumps for automatic wicket indication." },
  { name: "4 WAY SLEEVE", price: 14.99, image: "/images/products/accessories-clothing-4-way-sleeve.webp", category: "accessories", rating: 4.1, reviews: 23, description: "Multi-purpose arm sleeve for cricket." },
  { name: "PADDED SLEEVE", price: 14.99, image: "/images/products/accessories-clothing-padded-sleeve.webp", category: "accessories", rating: 4.2, reviews: 34, description: "Padded arm sleeve for batting protection." },
  { name: "COLORED SLEEVE", price: 30, image: "/images/products/accessories-clothing-colored-sleeve.webp", category: "accessories", rating: 4.0, reviews: 15, description: "Stylish colored sleeve for match wear." },
  { name: "LEGGUARD CLADIS", price: 23.49, image: "/images/products/accessories-clothing-legguard-cladis.webp", category: "accessories", rating: 4.2, reviews: 23, description: "Leg guard cladding for additional protection." },
  { name: "BATTING INNERS", price: 14.09, image: "/images/products/accessories-clothing-batting-inners.webp", category: "accessories", rating: 4.3, reviews: 67, description: "Inner batting gloves for comfort and sweat absorption." },
  { name: "FINGER CUT INNERS", price: 23.9, image: "/images/products/accessories-clothing-finger-cut-inners.webp", category: "accessories", rating: 4.4, reviews: 34, description: "Finger cut inner gloves for dexterity." },
  { name: "WK INNER GLOVES", price: 14, image: "/images/products/accessories-clothing-wk-inner-gloves.webp", category: "accessories", rating: 4.2, reviews: 18, description: "Youth wicket keeping inner gloves for extra comfort." },
  { name: "BATTING INNERS (Youth)", price: 14.9, image: "/images/products/accessories-clothing-batting-inners-youth.webp", category: "accessories", rating: 4.1, reviews: 15, description: "Youth batting inners for junior cricketers." },
  { name: "PANAMA HAT", price: 14, image: "/images/products/accessories-clothing-panama-hat.webp", category: "accessories", rating: 4.0, reviews: 12, description: "Classic Panama hat for sun protection on the field." },
  { name: "SUNGLASSES", price: 64.99, image: "/images/products/accessories-clothing-sunglasses.webp", category: "accessories", rating: 4.3, reviews: 34, description: "Performance sunglasses for outdoor cricket." },
  { name: "TOSS COIN", price: 4, image: "/images/products/accessories-clothing-toss-coin.webp", category: "accessories", rating: 4.1, reviews: 56, description: "Match toss coin for your cricket kit." },
  { name: "UMPIRE COUNTER", price: 0, image: "/images/products/accessories-clothing-umpire-counter.webp", category: "accessories", rating: 3.9, reviews: 8, description: "Umpire ball counter for match officiating." },
  { name: "HELMET NUTS", price: 9.99, image: "/images/products/accessories-clothing-helmet-nuts.webp", category: "accessories", rating: 4.0, reviews: 23, description: "Spare helmet nuts and bolts kit." },
  { name: "TENNIS BATTING GLOVES", price: 14.09, image: "/images/products/accessories-clothing-tennis-batting-gloves.webp", category: "accessories", rating: 4.1, reviews: 34, description: "Batting gloves for tennis ball cricket." },
  { name: "GRAY NICHOLLS MOP", price: 14.99, image: "/images/products/accessories-clothing-gray-nicholls-mop.webp", category: "accessories", rating: 4.3, reviews: 28, description: "Gray-Nicolls branded mop for pitch maintenance." },
];
